// World Cup 2026 — 32-team field
// Elo ratings from eloratings.net / footballratings.org (mid-June 2026 where available).
// "best" = best-ever World Cup finish, on a 1–5 scale: 1 = winner, 2 = runner-up,
// 3 = third place, 4 = fourth place / semi-finalist, 5 = quarter-finalist or worse.
// All 32 teams below are genuinely qualified for the 2026 World Cup.

const TEAMS = [
  { name: "Spain",          flag: "🇪🇸", elo: 2129, rank: 1,  best: 1, player: "Lamine Yamal" },
  { name: "Argentina",      flag: "🇦🇷", elo: 2128, rank: 2,  best: 1, player: "Lionel Messi" },
  { name: "France",         flag: "🇫🇷", elo: 2084, rank: 3,  best: 1, player: "Kylian Mbappe" },
  { name: "England",        flag: "🏴", elo: 2055, rank: 4,  best: 1, player: "Jude Bellingham" },
  { name: "Colombia",       flag: "🇨🇴", elo: 1998, rank: 5,  best: 5, player: "Luis Diaz" },
  { name: "Brazil",         flag: "🇧🇷", elo: 1978, rank: 6,  best: 1, player: "Vinicius Junior" },
  { name: "Portugal",       flag: "🇵🇹", elo: 1967, rank: 7,  best: 3, player: "Cristiano Ronaldo" },
  { name: "Netherlands",    flag: "🇳🇱", elo: 1944, rank: 8,  best: 2, player: "Virgil van Dijk" },
  { name: "Germany",        flag: "🇩🇪", elo: 1939, rank: 9,  best: 1, player: "Jamal Musiala" },
  { name: "Norway",         flag: "🇳🇴", elo: 1929, rank: 10, best: 5, player: "Erling Haaland" },
  { name: "Japan",          flag: "🇯🇵", elo: 1910, rank: 11, best: 5, player: "Takefusa Kubo" },
  { name: "Mexico",         flag: "🇲🇽", elo: 1896, rank: 12, best: 4, player: "Santiago Gimenez" },
  { name: "Croatia",        flag: "🇭🇷", elo: 1933, rank: 13, best: 2, player: "Luka Modric" },
  { name: "Switzerland",    flag: "🇨🇭", elo: 1897, rank: 14, best: 5, player: "Granit Xhaka" },
  { name: "Uruguay",        flag: "🇺🇾", elo: 1890, rank: 15, best: 1, player: "Federico Valverde" },
  { name: "Morocco",        flag: "🇲🇦", elo: 1898, rank: 16, best: 4, player: "Achraf Hakimi" },
  { name: "Belgium",        flag: "🇧🇪", elo: 1849, rank: 17, best: 3, player: "Kevin De Bruyne" },
  { name: "Senegal",        flag: "🇸🇳", elo: 1869, rank: 18, best: 5, player: "Sadio Mane" },
  { name: "Turkey",         flag: "🇹🇷", elo: 1880, rank: 19, best: 3, player: "Arda Guler" },
  { name: "Denmark",        flag: "🇩🇰", elo: 1864, rank: 20, best: 5, player: "Christian Eriksen" },
  { name: "United States",  flag: "🇺🇸", elo: 1822, rank: 21, best: 3, player: "Christian Pulisic" },
  { name: "Ecuador",        flag: "🇪🇨", elo: 1840, rank: 22, best: 5, player: "Moises Caicedo" },
  { name: "Austria",        flag: "🇦🇹", elo: 1820, rank: 23, best: 4, player: "David Alaba" },
  { name: "Sweden",         flag: "🇸🇪", elo: 1810, rank: 24, best: 2, player: "Alexander Isak" },
  { name: "Czechia",        flag: "🇨🇿", elo: 1795, rank: 25, best: 2, player: "Patrik Schick" },
  { name: "South Korea",    flag: "🇰🇷", elo: 1790, rank: 26, best: 4, player: "Son Heung-min" },
  { name: "Scotland",       flag: "🏴", elo: 1780, rank: 27, best: 5, player: "Scott McTominay" },
  { name: "Canada",         flag: "🇨🇦", elo: 1770, rank: 28, best: 5, player: "Alphonso Davies" },
  { name: "Saudi Arabia",   flag: "🇸🇦", elo: 1740, rank: 29, best: 5, player: "Salem Al-Dawsari" },
  { name: "Iran",           flag: "🇮🇷", elo: 1735, rank: 30, best: 5, player: "Mehdi Taremi" },
  { name: "Ivory Coast",    flag: "🇨🇮", elo: 1760, rank: 31, best: 5, player: "Simon Adingra" },
  { name: "Paraguay",       flag: "🇵🇾", elo: 1750, rank: 32, best: 5, player: "Julio Enciso" },
];
